### PR TITLE
Residual plots

### PR DESCRIPTION
**Pull request by phajy**
Draft plotting recipe for residual plots. Needs some updating to make the plots better, and to allow more user-defined options.

### CODE REVIEW

**Comment by phajy** [comment]
Here's an example residual plot.

residual_plot

Things I couldn't immediately figure out but would like to fix:

- Make the model line more of a "histogram" rather than just x error bars.
- Have a logarithmic x-axis but the labels to be, e.g., natural number instead of $10^\text{something}$.
- Keep the x tick marks on the upper panel
- Reduce the border between the top and bottom panel to zero without messing anything else up, e.g., the labels on the lower panel.
- I don't suppose there is any (easy!) way to have the test suite work on plots?

**Comment by phajy** [comment]
I rebased this branch. But perhaps I just wanted to merge the main branch into it. Hmm... not sure.

**Comment by fjebaker** [comment]
Hi @phajy ! This looks great! Thanks for the PR, will review it tomorrow in detail. The log axes with sensible labels is something I just hacked for the other plots, but it would be worth while writing a proper utility function for them, so that it's reusable between all the different plotting recipes.

And rebasing PR branches onto main is a common practice, and, in my opinion, much better than merging main into the PR branch. It means you just see the changed commits then, and the history is much more linear after merging.

**Comment by phajy** [comment]
@fjebaker - there were some problems with the error bars and statistics calculation. See the commit above which you might want to extract / move to a new branch / issue.

**Comment by fjebaker** [comment]
Hi @phajy addressed the error things in #94 which will be merged into main in a moment. Feel free to rebase your PR on main after that, else let me know and I can do that for you!

**Comment by phajy** [comment]
It is fine to merge this right now. We might want to make some cosmetic changes in the future, but this shouldn't hold things up.

**Comment by fjebaker** [comment]
There we go, commits squashed, edited, and rebased for merging!

**Comment by fjebaker** [comment]
Undid some of the changes in the error statistics commit, and formatted the tree with JuliaFormatter

**Pull request merged**
