### PR TITLE
Fixing bind mapping with multiple models

### PR DESCRIPTION
**Pull request by phajy**
This PR addresses #89 regarding a problem with `bind` if there are multiple models and datasets.

Once a parameter has been bound to another parameter it must relinquish the parameter number it had before being bound. This means that there is now a gap in the contiguous list of parameter numbers. Larger parameter numbers then need to be shuffled down by one to fill this gap, resulting in a contiguous list of parameters. The problem was that all later parameters in the lit were being decremented by 1 regardless of whether they were larger or not.

A test case has been added to check that `bind` works as anticipated for multiple models and datasets. Further tests could usefully be added.

Finally, there are lots of debugging `println` statements that can be removed once we're satisfied the code is working properly.

### CODE REVIEW

**Review by fjebaker — COMMENTED** [review]
Hi @phajy this looks good! I would ask for a few more test cases though, specifically
- 3 models, 1 bound parameter
- 3 models (2 the same, 1 different), bind one parameter between the two
- 2 models, both different, bind a parameter that is only in one model (check it does no-ops okay)

Have you tested it on your use case? Might be worth adding an integration test somewhere too, but maybe that's for a new PR. Let's get this one merged first.

**Review by phajy — COMMENTED** [review]
I'll add some test cases. Is it OK to use XSPEC models in the test? I want something with more than two parameters but all the current Julia additive models have two parameters. What do you recommend?

**Comment by phajy** [comment]
I've added some test cases. However, test case 3 suggested above (the no-op case) does not work. If you try to bind a parameter that is not in one of the models `_get_index_of_symbol` returns an error. Perhaps this function should just return `nothing` then we can get `bind!` to ignore `nothings`s. Not sure how this affects `_bind_pairs!` though.

Any suggestions?

**Review by fjebaker — APPROVED** [review]
Thanks Andy!

**Comment by fjebaker** [comment]
Well noticed, I think we should address that in a new PR though. This one has the test suite passing so I think it's good to merge.

**Comment by phajy** [comment]
I should get rid of the debug print statements - do you want me to create a new PR for that?

**Comment by fjebaker** [comment]
I think it's fine just to do it in this PR. If you could add one more commit removing the debug statements :+1:

**Comment by phajy** [comment]
Done! Print statements removed.

Note, however, that the test suite is only passing because I have commented out the code that tests

> 2 models, both different, bind a parameter that is only in one model (check it does no-ops okay)

because it does not work yet. See https://github.com/fjebaker/SpectralFitting.jl/pull/90#issuecomment-2093110416 above.

**Comment by phajy** [comment]
Sorry, accidentally closed the PR. Happy for you to merge.

**Review by fjebaker — APPROVED** [review]

**Pull request merged**
